print("Calculate your age. >>")
year = input("You enter the year: ")
birthyear = input("Enter your year of birth: ")
conclusion = int(year) - int(birthyear)
print(">> "+str(conclusion)+" You are years old.")